spring:
  application:
    name: service-feign
  zipkin:
    base-url: http://localhost:8770

server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

