spring:
  application:
    name: config-server
  rabbitmq:
    host: localhost
    port: 5672
    username: springcloud
    password: 123abc
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lizhe1993/springcloud-study
          search-paths: data-config
      label: master
    bus:
      trace:
        enabled: true

server:
  port: 8766

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  security:
    enabled: false

